name: Petclinic CI with JFrog

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: petclinic
      IMAGE_TAG: 1.1.0
      BUILD_NAME: petclinic-build
      BUILD_NUMBER: ${{ github.run_number }}
      JFROG_URL: trialny4vkg.jfrog.io
      DOCKER_REPO: petclinic-docker-local
      MAVEN_REPO: petclinic-maven-local
    steps:
    #  Checkout source
    - name: Checkout source
      uses: actions/checkout@v4

    # Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    # Setup JFrog CLI
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: https://trialny4vkg.jfrog.io
        JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
    - name: Configure Maven with Artifactory
      run: |
        jfrog mvn-config \
          --server-id-resolve=artifactory \
          --server-id-deploy=artifactory \
          --repo-resolve-releases=${MAVEN_REPO} \
          --repo-resolve-snapshots=${MAVEN_REPO} \
          --repo-deploy-releases=${MAVEN_REPO} \
          --repo-deploy-snapshots=${MAVEN_REPO}

    - name: Maven Build with JFrog
      working-directory: spring-petclinic
      run: |
        jfrog mvn clean package -DskipTests \
          --build-name=${BUILD_NAME} \
          --build-number=${BUILD_NUMBER}

    # Docker login (ONLY once)
    - name: Docker Login to Artifactory
      uses: docker/login-action@v2
      with:
        registry: trialny4vkg.jfrog.io
        username: ${{ secrets.JFROG_USER }}
        password: ${{ secrets.JFROG_TOKEN }}

    #  Docker build with JFrog build-info
    - name: Docker Build
      working-directory: spring-petclinic
      run: |
        jfrog docker build \
          --build-name=${BUILD_NAME} \
          --build-number=${BUILD_NUMBER} \
          -t ${JFROG_URL}/${DOCKER_REPO}/${IMAGE_NAME}:${IMAGE_TAG} .
    - name: Docker Push
      run: docker push ${JFROG_URL}/${DOCKER_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
    # Publish build-info
    - name: Publish Build Info
      run: |
        jfrog rt build-publish ${BUILD_NAME} ${BUILD_NUMBER}
    # Xray Scan
    - name: Xray Scan
      run: |
        jfrog build-scan ${BUILD_NAME} ${BUILD_NUMBER}