name: Petclinic CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      working-directory: spring-petclinic
      run: mvn -B clean package -DskipTests

    - name: Docker Build
      working-directory: spring-petclinic
      run: docker build -t petclinic:1.1.0 .
    - name: Docker Login to Artifactory
      env:
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
      run: echo "${JFROG_TOKEN}" | docker login trialny4vkg.jfrog.io -u "${JFROG_USER}" --password-stdin

    - name: Tag and Push Image to Artifactory
      run: |
        docker tag petclinic:1.0 trialny4vkg.jfrog.io/petclinic-docker-local/petclinic:1.1.0
        docker push trialny4vkg.jfrog.io/petclinic-docker-local/petclinic:1.1.0
