name: Petclinic CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'    # fetch submodule contents
        fetch-depth: 0
    - name: Show workspace and locate pom.xml
      run: |
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
        pwd
        ls -la
        echo "Top-level tree (depth=3)"
        find . -maxdepth 3 -type d -print
        echo "Find pom.xml"
        find . -name pom.xml -print || true

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      working-directory: spring-petclinic
      run: mvn -B clean package -DskipTests

    - name: Docker Build
      working-directory: spring-petclinic
      run: docker build -t petclinic:1.1.0 .
    - name: Docker Login to Artifactory
      uses: docker/login-action@v2
      with:
        registry: trialny4vkg.jfrog.io
        username: ${{ secrets.JFROG_USER }}
        password: ${{ secrets.JFROG_TOKEN }}
    - name: Tag and Push Image to Artifactory
      working-directory: spring-petclinic
      run: |
        docker tag petclinic:1.0 trialny4vkg.jfrog.io/petclinic-docker-local/petclinic:1.1.0
        docker push trialny4vkg.jfrog.io/petclinic-docker-local/petclinic:1.1.0
